// Dependency-free browser verification: Node built-ins + Chrome supplied by the CI runner.
import{createServer}from'node:http';import{spawn}from'node:child_process';import{readFile,writeFile,mkdir}from'node:fs/promises';import assert from'node:assert/strict';
const out='test-results';await mkdir(out,{recursive:true});const html=await readFile('index.html');const server=createServer((q,r)=>{r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});r.end(html)});await new Promise(r=>server.listen(8080,'127.0.0.1',r));
const chrome=spawn('/usr/bin/google-chrome',['--headless=new','--no-sandbox','--disable-extensions','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--remote-debugging-port=9222','--user-data-dir=/tmp/synth-fab-chrome','about:blank'],{stdio:'ignore'});
const sleep=t=>new Promise(r=>setTimeout(r,t));let ws,id=0,pending=new Map(),errors=[],checks=[];
function send(method,params={}){return new Promise((resolve,reject)=>{const n=++id,timer=setTimeout(()=>{pending.delete(n);reject(Error('CDP timeout: '+method))},20000);pending.set(n,{resolve:r=>{clearTimeout(timer);resolve(r)},reject:e=>{clearTimeout(timer);reject(e)}});ws.send(JSON.stringify({id:n,method,params}))})}
async function ev(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function until(expression,timeout=45000){const t=Date.now();while(Date.now()-t<timeout){if(await ev(expression))return;await sleep(250)}throw Error('Timed out: '+expression)}
async function shot(name){const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(`${out}/${name}.png`,Buffer.from(r.data,'base64'))}
async function click(s){await ev(`document.querySelector(${JSON.stringify(s)}).click()`)}
async function check(name,fn){await fn();checks.push('PASS — '+name);console.log('::notice::PASS: '+name)}
try{let page;for(let n=0;n<60;n++){try{const tabs=await(await fetch('http://127.0.0.1:9222/json')).json();page=tabs.find(t=>t.type==='page'&&t.url==='about:blank')||tabs.find(t=>t.type==='page');if(page)break}catch{}await sleep(250)}assert(page,'Chrome page target not available');ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);else if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')console.log('::warning::Browser: '+m.params.args.map(a=>a.description||a.value||a.type).join(' ').replaceAll('\n','%0A'))};
await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});const nav=await send('Page.navigate',{url:'http://127.0.0.1:8080/'});assert(!nav.errorText,nav.errorText);
await check('WebGL and Three.js r128 initialize',async()=>{await until('typeof engine!=="undefined" && (!!engine||!document.querySelector("#retry").hidden)');assert(await ev('!!engine'),await ev('document.querySelector("#loading-text").textContent'));assert.equal(await ev('THREE.REVISION'),'128')});await sleep(1000);await shot('01-desktop-hero');
await check('Desktop layout has no horizontal overflow',async()=>assert(await ev('document.documentElement.scrollWidth<=innerWidth+1')));
await check('Material and orbit controls',async()=>{await click('[data-material="3"]');assert.match(await ev('document.querySelector("#material-name").textContent'),/Cyan/);assert.equal(await ev('document.querySelector("#orbit-btn").getAttribute("aria-pressed")'),'true')});
await check('Reconstruction and exploded shell',async()=>{await click('[data-step="2"]');await sleep(1500);await click('#explode');assert.equal(await ev('document.querySelector("#explode").getAttribute("aria-pressed")'),'true')});await shot('02-reconstruction');
await check('Layer scrub and G-code readout',async()=>{await click('[data-step="3"]');await sleep(1500);await ev('document.querySelector("#layer-slider").value=400;document.querySelector("#layer-slider").dispatchEvent(new Event("input"))');assert.equal(await ev('document.querySelector("#layer-value").textContent'),'400');assert.equal(await ev('document.querySelector("#gcode-z").textContent'),'80.00');assert(await ev('!document.querySelector("#slice-hud").hidden'))});await shot('03-slicer');
await check('Physical build plate handoff',async()=>{await click('[data-step="4"]');await sleep(1500);assert.match(await ev('document.querySelector("#stage-status").textContent'),/BUILD PLATE/)});await shot('04-physical');
await check('All STL and 3MF exports',async()=>{const records=await ev(`['chameleon','totem','planter'].map(kind=>{const s=engine.exportSTL(kind),z=engine.export3MF(kind);return {kind,bytes:s.byteLength,triangles:new DataView(s).getUint32(80,true),zip:z.length,signature:new DataView(z.buffer).getUint32(0,true),end:new DataView(z.buffer).getUint32(z.length-22,true)}})`);for(const r of records){assert(r.triangles>100);assert.equal(r.bytes,84+r.triangles*50);assert.equal(r.signature,0x04034b50);assert.equal(r.end,0x06054b50)}await writeFile(`${out}/exports.json`,JSON.stringify(records,null,2));for(const kind of ['chameleon','totem','planter'])await writeFile(`${out}/${kind}.3mf`,Buffer.from(await ev(`Array.from(engine.export3MF('${kind}'))`)))});
await check('Simulator estimates and cancellation',async()=>{await ev('document.querySelector("#lab").scrollIntoView({behavior:"instant"})');await click('#simulate');await until('!document.querySelector("#receipt").hidden');assert.equal(await ev('document.querySelector("#receipt-time").textContent'),'1h 42m');assert.equal(await ev('document.querySelector("#receipt-weight").textContent'),'48g');await click('[data-preset="Parametric Cable Organizer"]');await click('#simulate');await click('#cancel-sim');assert.match(await ev('document.querySelector("#sim-status").textContent'),/CANCELLED/);assert.equal(await ev('document.querySelector("#prompt").value'),'Parametric Cable Organizer')});await shot('05-simulator');
await check('Comparison slider and asset dialog',async()=>{await ev('const r=document.querySelector(".compare input");r.value=73;r.dispatchEvent(new Event("input"))');assert.equal(await ev('document.querySelector(".compare").style.getPropertyValue("--split")'),'73%');await click('[data-asset="1"]');assert(await ev('document.querySelector("#asset-dialog").open'));assert.match(await ev('document.querySelector("#asset-title").textContent'),/Monolith/);await ev('document.querySelector("#asset-dialog").close()')});
await check('Mobile overflow, touch scrolling, menu and help',async()=>{await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await ev('window.scrollTo({top:0,behavior:"instant"})');await sleep(1600);await click('#reset-view');assert(await ev('document.documentElement.scrollWidth<=innerWidth+1'),await ev('JSON.stringify({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll("body *")].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,id:e.id,class:e.className}))})'));assert.equal(await ev('document.querySelector("#scene").style.touchAction'),'pan-y');await click('#menu-btn');assert.equal(await ev('document.querySelector("#menu-btn").getAttribute("aria-expanded")'),'true');await click('#menu-btn');await click('#help-quick');assert(await ev('document.querySelector("#help-dialog").open'));await ev('document.querySelector("#help-dialog").close()')});await shot('06-mobile-hero');
await check('Reduced motion',async()=>{await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Page.reload');await sleep(1000);await until('typeof engine!=="undefined"&&!!engine');assert.equal(await ev('document.querySelector("#pause-btn").getAttribute("aria-pressed")'),'true')});assert.equal(errors.length,0,errors.join('\n'));console.log('::notice::ALL BROWSER CHECKS PASSED');
}catch(e){checks.push('FAIL — '+e.message);console.error('::error::'+e.stack.replaceAll('\n','%0A'));process.exitCode=1;try{console.error('::notice::'+await ev('JSON.stringify({url:location.href,ready:document.readyState,loading:document.querySelector("#loading-text")?.textContent,three:typeof THREE,engine:typeof engine})'));await shot('failure')}catch{}}
finally{await writeFile(`${out}/report.md`,'# SYNTH//FAB verification\n\n'+checks.map(x=>'- '+x).join('\n')+'\n\n'+errors.join('\n'));ws?.close();chrome.kill('SIGTERM');server.close()}
